### ISSUE TITLE
Game feedback

### ISSUE THREAD

**Issue by babypeach7929** [xd3v0nx/Project_EscapingAlderwood#3]
Game Version:
[v1.0.0]

Device & OS Version:
[e.g., Samsung Galaxy S21, Android 12]

Describe the Issue:
There are several issues reported related to game characters, their behavior, and game items.

Steps to Fix the Issues & Find the Solutions:

Check character Thomas's color-changing mechanics.
Investigate the wall collision mechanism for guards.
Evaluate the user interface for game restart instructions or buttons.
Reassess dagger mechanics against guards.
Improve visibility and usability of the dagger item.
Remove Mabel aging mentions
Rectify guard movement and collision, especially backward motion.
Expected Behavior:

Thomas should maintain a consistent color.
Guards shouldn't be able to detect or move through walls.
Restarting the game should be intuitive and easy.
Daggers should interact properly with guards.
Dagger should be visible and user-friendly.
Remove any mention of Mabel aging
Guards shouldn't walk backward through walls.
Actual Behavior:

Thomas turns from blue to green.
A guard detected and caught Mabel through a wall.
Difficulty in finding a way to restart the game.
Dagger doesn't kill guards.
Dagger is hard to see and use.
Mabel ages without clear reason.
Guard was observed walking backward through a wall.
Screenshots/Video:
[Attach any relevant screenshots or videos if possible.]

Additional Comments:
The reported issues greatly affect the gameplay experience. Proper explanations or corrections for the behaviors mentioned would help in enhancing user experience.

**Comment by xd3v0nx** [comment]
@isnizal  I need you to go through these issues from your previous development, please fix from my first Game Tester's Feedback; once these basic issues are fixed, we can proceed to making more specific changes on advancing the narrative and game play, but these are basic issues that should not have been found in the first version. Please advise, and thank you!

**Comment by isnizal** [comment]
https://github.com/xd3v0nx/Project_EscapingAlderwood/commit/1babb9c3de0c0c0d4f77c4ec336928023341093a
here is the link I commit to the related issue:
1)Changes Thomas's indicator from normal to blue and hot by adjusting the float and adding a normal float.
2)Fix Guard detected and caught Mabel through a wall.
3)Add restart UI after retrying 3 times.
4)Dagger will deactivate guards.
5)Resize the dagger a little bit bigger in scenes.
6)Remove Mabel's aging UI process.
7)Fix Guard walking through a wall on guard scripts.
