### ISSUE TITLE
[v1.1.1][The Dungeon Maze][Faulty Experience]

### ISSUE THREAD

**Issue by xd3v0nx** [xd3v0nx/Project_EscapingAlderwood#6]
Game Version:
[v1.1.1]

Device & OS Version:
Android OS

Feedback: Please Implement Changes
You know what would be cool? If we could control the player with our finger instead of the left, right, up, down controls. I think that is what we need to do. Implement player controls that let you move Mabel, the main character, with your finger. Please make this change. When a guard comes after Mabel, she needs a way to strike the enemies. I was thinking a swiping motion. So as you approach the enemy by holding the character with your finger, now an enemy is coming your way, change the player controls to a swipe. Swipe in the direction of where you want to slash the dagger. When you swing and swipe at the enemies, the guards, you can stun them and allow you to get away, but you only have 1-2 seconds that the guard remains stunned; after 3 strikes of the dagger, the guard or enemy falls down and resurrects as the Accursed. I want the guard to rise, resembling the undead, but in Alderwood they are known as The Accursed. The Accursed die in one slash. I also want to enable Mabel the ability to run. She can walk AND run. Enable that in the controls. I want to add more obstacles, like The Accursed emerging from the walls, some of the walls contain traps. Basically, I want the Accursed creatures to leap from the wall and chase after Mabel. Please add these to the next version v1.2.0; also, create a Weapon Wheel, or Weapon Arsenal, 4 Slots. Give the Weapon Wheel 4 slots. The dagger will be stored in the weapon wheel, followed by any weapons or potions Mabel gets along the way. Give Mabel a Health Gauge, too. A simple Health gauge, red, with 3 hits and then she has to restart. Please implement these features into v1.2.0; do not forget to provide instructions in a little question mark icon button, small, in the bottom right hand corner, adjacent to the Weapon Wheel. Put a "Pause" button next to the question mark icon button, too. We need a way to Pause the game. @isnizal  @xd3v0nx

**Comment by isnizal** [comment]
> Game Version:
> [v1.1.1]
> 
> Device & OS Version:
> Android OS
> 
> Feedback: Please Implement Changes
> You know what would be cool? If we could control the player with our finger instead of the left, right, up, down controls. I think that is what we need to do. Implement player controls that let you move Mabel, the main character, with your finger. Please make this change. When a guard comes after Mabel, she needs a way to strike the enemies. I was thinking a swiping motion. So as you approach the enemy by holding the character with your finger, now an enemy is coming your way, change the player controls to a swipe. Swipe in the direction of where you want to slash the dagger. When you swing and swipe at the enemies, the guards, you can stun them and allow you to get away, but you only have 1-2 seconds that the guard remains stunned; after 3 strikes of the dagger, the guard or enemy falls down and resurrects as the Accursed. I want the guard to rise, resembling the undead, but in Alderwood they are known as The Accursed. The Accursed die in one slash. I also want to enable Mabel the ability to run. She can walk AND run. Enable that in the controls. I want to add more obstacles, like The Accursed emerging from the walls, some of the walls contain traps. Basically, I want the Accursed creatures to leap from the wall and chase after Mabel. Please add these to the next version v1.2.0; also, create a Weapon Wheel, or Weapon Arsenal, 4 Slots. Give the Weapon Wheel 4 slots. The dagger will be stored in the weapon wheel, followed by any weapons or potions Mabel gets along the way. Give Mabel a Health Gauge, too. A simple Health gauge, red, with 3 hits and then she has to restart. Please implement these features into v1.2.0; do not forget to provide instructions in a little question mark icon button, small, in the bottom right hand corner, adjacent to the Weapon Wheel. Put a "Pause" button next to the question mark icon button, too. We need a way to Pause the game. @isnizal  @xd3v0nx 

That a lot of list need to do and good idea for next version. There is pause button on the top right of screen but I had not implement any icon yet.

**Comment by xd3v0nx** [comment]
@isnizal  let's get started on this ASAP. I would like to get this done by Monday if possible! :) v1.2.0

**Comment by isnizal** [comment]
https://github.com/xd3v0nx/Project_EscapingAlderwood/tree/6-v111the-dungeon-mazefaulty-experience Update v1.2.0
