### ISSUE TITLE
Few issues i noticed 

### ISSUE THREAD

**Issue by Kyree30** [xd3v0nx/Project_EscapingAlderwood#7]
The controls feel problematic – when I press the "up" button, the character moves left. Additionally, there are instances where the character moves on its own without any input. The pop-up details should have a time limit; for example, when it advises avoiding the guard. Also, the distance at which the guard catches the character seems too short, as I've been caught even when far away.

**Comment by isnizal** [comment]
there is a reason why the control moves left after you press up, the code shares a similar script with the touch screen input from v 1.2.0. I cannot find the character move on its own Like you said what happened before that Did you press the button or not? I will add the pop-up limit to the list. I do not understand what you saying "guard catches the character seems too short, as I've been caught even when far away". After you have insight into the guard, they will try to pursue you even after you are already far away.

**Comment by isnizal** [comment]
The guard will try to pursue you even far away. You cannot hide even after being identified.

**Comment by isnizal** [comment]
I fixed the related issues, you can read the description of development at a branch.
