### ISSUE TITLE
One more

### ISSUE THREAD

**Issue by Kyree30** [xd3v0nx/Project_EscapingAlderwood#8]
Instead of using a 4-button control scheme, perhaps consider implementing an analog mode for enhanced mobility. This could provide smoother movement and more precise control for the character.

**Comment by CB-PORTAL** [comment]
Will discuss with the team @isnizal  thoughts? We want to provide the best flexibility for player control

**Comment by isnizal** [comment]
Good idea, I've seen some analog sticks before so that will not be a problem. The analog sticks should have been like the touchscreen version V1.2.0. I just found out that it should be like that Do you have any other suggestions on what should I use?

**Comment by isnizal** [comment]
I think has smoother movement and precise control.
