### ISSUE TITLE
[v1.2.1][Level 1][The Dungeon Maze][Feedback for improvements and modifications to be implemented in the game update v1.2.2]

### ISSUE THREAD

**Issue by CB-PORTAL** [xd3v0nx/Project_EscapingAlderwood#9]
Game Version:
[v1.2.1]

Device & OS Version:
[Android OS - Prototype]

Describe the Issue:
Feedback for improvements and modifications to be implemented in the game update v1.2.2.

Steps to Fix the Issues & Find the Solutions:

Background Music:
Implement a horror music track to play in the background to enhance the game atmosphere.

Interface Adjustments:
Relocate the current large bubble knife from the center to the right side of the screen.
Shrink the instruction boxes to fit the 1 sentence text.
Move the bubble knife to the bottom right corner where other buttons are.
The exclamation point in the yellow bubble should be replaced with a question mark.
Remove the weapon wheel and simplify the weapon selection process by making the weapons clickable buttons, starting with the knife. The dagger should be in a button like the pause button and the question mark button that displays instructions on game play mechanics.

Weapon Configuration:
All weapons, starting with the dagger, should appear in a bubble button format at the bottom right.
Make weapon buttons smaller, similar to the pause and instructions button.
Remove the large knife button from the center of the screen.

Control Adjustments:
Replace current movement controls with an analog stick control system.
Add a Control System around Mabel, arrows depicted in the photo, so that players know that swiping up, down, left, right, moves the character in that direction. I like that, but we can't have it conflict with the analog control system when you create it
Preserve the script for the touch screen controls but remove them from the game as they conflict with character movement for now. Maybe we will implement a dual player control system in future versions. 

Expected Behavior:
A smoother gameplay experience with intuitive controls, minimized interface distractions, and immersive background music.

Actual Behavior:
Game currently has large buttons disrupting view, clashing control schemes, and lacks desired atmospheric music.

Screenshots/Video:
![Update Button Controls](https://github.com/xd3v0nx/Project_EscapingAlderwood/assets/132307280/d9e26a3a-14a3-4679-ac0a-783ea9f10daa)

Additional Comments:
It is imperative to implement all the suggested changes in v1.2.2. The goal is to refine the gameplay experience, ensuring it is user-friendly and engaging.

**Comment by CB-PORTAL** [comment]
@isnizal  please begin v1.2.2 on these changes. We are ready. Additionally, one aspect not mentioned, the guard needs to touch mabel, so you need to close in the trigger box around mabel to ensure closer contact of the guard captures mabel; Mabel needs to be able to use the dagger without getting caught right away. Allow Mabel to use the dagger to stun or slow down the guard. Let's start there. We do have other things to do but this is a good start in addition to the above feedback. Thanks.

**Comment by isnizal** [comment]
I push to the branch v1.2.2 as new changes.
